/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as external from "./external";
export type { external };
export type { Lock } from "./Lock";
export type { LockUpgr } from "./LockUpgr";
