/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICodeTrust,
  ICodeTrustInterface,
} from "../../../contracts/interfaces/ICodeTrust";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "trustedCode",
        type: "address",
      },
      {
        internalType: "address",
        name: "by",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "extTimestamp",
        type: "uint256",
      },
    ],
    name: "isTrustedCode",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "trustedCode",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
    ],
    name: "trustCodeAt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "trustedCode",
        type: "address",
      },
    ],
    name: "untrustCodeAt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICodeTrust__factory {
  static readonly abi = _abi;
  static createInterface(): ICodeTrustInterface {
    return new utils.Interface(_abi) as ICodeTrustInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICodeTrust {
    return new Contract(address, _abi, signerOrProvider) as ICodeTrust;
  }
}
