/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "CodeTrust",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CodeTrust__factory>;
    getContractFactory(
      name: "DumbExample",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DumbExample__factory>;
    getContractFactory(
      name: "ICodeTrust",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICodeTrust__factory>;
    getContractFactory(
      name: "ProxyAdmin",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProxyAdmin__factory>;
    getContractFactory(
      name: "TransparentUpgradeableProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransparentUpgradeableProxy__factory>;

    getContractAt(
      name: "CodeTrust",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CodeTrust>;
    getContractAt(
      name: "DumbExample",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DumbExample>;
    getContractAt(
      name: "ICodeTrust",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICodeTrust>;
    getContractAt(
      name: "ProxyAdmin",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ProxyAdmin>;
    getContractAt(
      name: "TransparentUpgradeableProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TransparentUpgradeableProxy>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
